#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.0.{build}
os: Visual Studio 2017
install:
  - ps: . .\AppVeyor\AppVeyorInstall.ps1

environment:
  ModuleName: CodeAudit
  $DebugPreference = "Continue"
#---------------------------------# 
#      build configuration        # 
#---------------------------------# 
build_script: 
  - ps: . .\AppVeyor\AppVeyorBuild.ps1

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
test_script: 
  - ps: . .\AppVeyor\AppVeyorTest.ps1

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
# deploy_script: 
#  - ps: . .\AppVeyor\AppveyorDeploy.ps1
